### ISSUE TITLE
cli param to open directory

### ISSUE THREAD

**Issue by dgoosens** [Gilad-Kutiel-App/jumpfm#2]
Hi,

As a Linux user, I spend quite some time on the command line...  
Would be nice if I where able to specify if a directory when launching jumpfm from the cli

```bash
# specify location
jumpfm /var/www

# current directory
jumpfm .
```

Started playing with **jumpfm** yesterday and already loving it...

**Comment by gkutiel** [comment]
You can do it now with this add-on https://www.npmjs.com/package/jumpfm-cd-argv
Currently, however you need to specify the full path, but you can probably wrap it with a bash script that do whatever you want.

**Comment by dgoosens** [comment]
awesome !

Thanks
